### ISSUE TITLE
Plugin causes an error when loading PKHeX

### ISSUE THREAD

**Issue by pollyevamay** [foohyfooh/PKHeXSortingPlugin#3]
Causes error when PKHeX 22.06.01 or 22.05.08 is run. 

![image](https://user-images.githubusercontent.com/74987674/172060374-4d7c95af-e69d-4614-a7ff-07c31f032dbb.png)
[Error Log](https://pastebin.com/rvpFc8ZF)

I have no other plugins installed, tested on fresh downloads of PKHeX too

**Comment by foohyfooh** [comment]
Does this issue occur even with ublocking the DLL like the Project Pokemon gif below shows?
![Unblock DLL](https://projectpokemon.org/images/wallpaper/how-to-unblock.gif)

**Comment by pollyevamay** [comment]
That fixed it perfectly, thank you for the solution and the latest update!
