### ISSUE TITLE
Sort option does not show up in the tools category.

### ISSUE THREAD

**Issue by coolbond1** [foohyfooh/PKHeXSortingPlugin#5]
after downloading the latest version and putting it in the plugins folder there is no option to actually sort the boxes at all.

**Comment by foohyfooh** [comment]
Does this occur after unblocking the plugin like [the instructions](https://github.com/foohyfooh/PKHeXSortingPlugin#instructions) say?

**Comment by coolbond1** [comment]
The option is not available for me, maybe its a win11 thing.

I have the auto legality plugin and that one works properly.

**Comment by foohyfooh** [comment]
Can you try the steps outlined on https://winaero.com/how-to-unblock-files-downloaded-from-the-internet-in-windows-11/ to unblock the files?

**Comment by coolbond1** [comment]
It worked had to use the powershell command.
