### ISSUE TITLE
About NET7.0 and translations

### ISSUE THREAD

**Issue by pplloufh** [foohyfooh/PKHeXSortingPlugin#6]
When will NET 7.0 be updated?
Will you add language files like those PKHeX has to your plugins?
I will contribute to the translation of this plugin in Chinese.

**Comment by foohyfooh** [comment]
Commit 0976ae2646d62da8ddaa0c14235776ca12085334 now adds support for .NET 7.0.
Not sure about if I will add language file support for this plugin.

**Comment by pplloufh** [comment]
Okay! I'm glad to get your reply:)
